services:
  postgres:
    image: postgres
    container_name: MP2I_PostgreSQL
    environment:
      - POSTGRES_DB=MP2I
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#    ports:
#      - "2345:5432"
    volumes:
      - bot_postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d MP2I"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  bot:
    container_name: MP2I_Bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/MP2I/logs
    env_file:
      - .env
    environment:
      ENVIRONMENT: development
      DATABASE_URL: postgresql+psycopg2://root:root@postgres:5432/MP2I
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

volumes:
  bot_postgresql_data:
